# -*- coding: utf-8 -*-
"""Python_ilk_deneme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19AJAYz4J6zpVigYRteWeqwmXERmHnpNC

python programlama dilinde print komutu ekrandan kullanıcıya bilgi veren bir koddur.
06.08.2024 Veri Yapıları Ve Algoritmaları dersi ilk çıktısıdır.
"""

print("merhaba avcilar") #print ekrana cikti veren bir koddur

import sys #import python programlama dilinde yazılıma kütüphane eklemeye yarayan bir kod bloğudur.
print(sys.version)

from google.colab import drive #google colab - drive bağlantısı
drive.mount('/content/drive')



import os
os.chdir('/content/drive/My Drive/VERIYAPILARI_ISTKA')
! pwd # bize kodun çıktısını dosya yolu olarak veren kod bloğudur.